name: release
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
    paths:
      - "SA-CrowdstrikeDevices/**"

jobs:
  call-packaging-workflow:
    uses: ZachTheSplunker/app-wfa/.github/workflows/release.yml@main
    with:
      package-name: SA-CrowdstrikeDevices